version: '3'

services:
  authentication:
    build: .
    depends_on:
      - keycloak
    #networks:
    #  - auth_network


  database:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: placeholder    #replace
    #networks:
    #  - auth_network

  keycloak:
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: placeholder        #replace

      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd  #replace
      #PROXY_ADDRESS_FORWARDING: "true"
      #REDIRECT_SOCKET: "proxy-https"
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8080:8080
    depends_on:
      - database
    #networks:
    #  - auth_network

volumes:
  postgres_data:
    driver: local

#networks:
#  auth_network: