version: '3.4'

services:
  #auth_interface:
  #  build: .
  #  depends_on:
  #    - keycloak
  #  environment:
  #    ADMIN_USER: ${ADMIN_USER}
  #    ADMIN_PASS: ${ADMIN_PASS}
  #    ADMIN_REALM: ${ADMIN_REALM}
  #    ADMIN_CLIENT: ${ADMIN_CLIENT}
  #    KEYCLOAK_URL: ${KEYCLOAK_URL}
  #    KEYCLOAK_REALM: ${KEYCLOAK_REALM}
  #    KEYCLOAK_CLIENT: ${KEYCLOAK_CLIENT}
  #    AUTH_PORT: ${AUTH_PORT}
  #  networks:
  #    - auth_network

  postgres:
    image: postgres:13.2
    volumes:
      - postgres_data:/usr/apps/authentication-stack/postgres_data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - auth_network

  keycloak:
    image: jboss/keycloak:13.0.0
    depends_on:
      - postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      KEYCLOAK_USER: ${ADMIN_USER}
      KEYCLOAK_PASSWORD: ${ADMIN_PASS}
    ports:
      - "8080:8080"
    networks:
      - auth_network

networks:
  auth_network:
volumes:
  postgres_data: