version: '3.4'

services:
  #auth_interface:
  #  build: .
  #  depends_on:
  #    - keycloak
  #  environment:
  #    AUTH_USER: ${ADMIN_USER}
  #    AUTH_PASSWORD: ${ADMIN_PASSWORD}
  #  networks:
  #    - auth_network

  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - auth_network

  keycloak:
    depends_on:
      - postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      KEYCLOAK_USER: ${ADMIN_USER}
      KEYCLOAK_PASSWORD: ${ADMIN_PASS}
    image: jboss/keycloak:13.0.0
    ports:
      - "8080:8080"
    networks:
      - auth_network

networks:
  auth_network:
